USE [PURC]
GO
/****** Object:  Table [dbo].[PURC_PO_D_PRICE]    Script Date: 10/18/2019 12:18:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PURC_PO_D_PRICE](
	[id] [uniqueidentifier] NOT NULL,
	[kd_stok] [varchar](22) NOT NULL,
	[no_po] [varchar](50) NOT NULL,
	[last_price] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_PURC_PO_D_PRICE] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PURC_PO_D_PRICE] ADD  CONSTRAINT [DF_PURC_PO_D_PRICE_id]  DEFAULT (newid()) FOR [id]
GO
ALTER TABLE [dbo].[PURC_PO_D_PRICE] ADD  CONSTRAINT [DF_PURC_PO_D_PRICE_kd_stok]  DEFAULT ('') FOR [kd_stok]
GO
ALTER TABLE [dbo].[PURC_PO_D_PRICE] ADD  CONSTRAINT [DF_PURC_PO_D_PRICE_no_po]  DEFAULT ('') FOR [no_po]
GO
ALTER TABLE [dbo].[PURC_PO_D_PRICE] ADD  CONSTRAINT [DF_PURC_PO_D_PRICE_last_price]  DEFAULT ((0)) FOR [last_price]
GO
