USE [INV]
GO

/****** Object:  Index [INV_STOK_GUDANG_idx]    Script Date: 10/18/2019 9:42:19 AM ******/
DROP INDEX [INV_STOK_GUDANG_idx] ON [dbo].[INV_STOK_GUDANG]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [INV_STOK_GUDANG_idx]    Script Date: 10/18/2019 9:42:19 AM ******/
CREATE NONCLUSTERED INDEX [INV_STOK_GUDANG_idx] ON [dbo].[INV_STOK_GUDANG]
(
	[bultah] ASC,
	[kd_stok] ASC
)
INCLUDE([akhir_qty]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [NonClusteredIndex-20191017-204344Y] ON [dbo].[INV_STOK_SALDO]
(
	[kd_stok] ASC,
	[bultah] ASC,
	[Kd_Cabang] ASC
)
INCLUDE([nilai_rata]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [NonClusteredIndex-20191018-093335] ON [dbo].[INV_GUDANG_OUT_D]
(
	[kd_stok] ASC,
	[blthn] ASC
)
INCLUDE([no_ref],[no_ref2],[tipe_trans],[qty_out],[gudang_asal],[keterangan],[Last_Create_Date]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [NonClusteredIndex-20191018-093719] ON [dbo].[INV_GUDANG_IN_D]
(
	[kd_stok] ASC,
	[blthn] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

USE [SALES]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [NonClusteredIndex-20191018-093206]    Script Date: 10/18/2019 9:44:45 AM ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20191018-093206] ON [dbo].[SALES_SO]
(
	[No_sp] ASC
)
INCLUDE([Atas_Nama]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [SALES]
GO


USE [SIF]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [NonClusteredIndex-20191018-090741]    Script Date: 10/18/2019 9:45:31 AM ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20191018-090741] ON [dbo].[SIF_Barang]
(
	[Kode_Barang] ASC,
	[Nama_Barang] ASC,
	[kd_jns_persd] ASC,
	[Rec_Stat] ASC
)
INCLUDE([Kd_Cabang],[Kd_Satuan],[kd_jenis],[rek_persediaan]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


